### ISSUE TITLE
Code explanation for "is_array(reset($values))"

### ISSUE THREAD

**Issue by vlakoff** [staudenmeir/laravel-upsert#1]
Hi @staudenmeir,

I have looked a bit at the code, and there is something I don't understand:
in [Builder.php](https://github.com/staudenmeir/laravel-upsert/blob/master/src/Eloquent/Builder.php) there is this code:

```php
if (!is_array(reset($values))) {
    $values = [$values];
}
```

(note that `$values` parameter is typehinted as array scalar)

The `is_array()` test seems superfluous (it's forcibly an array),
and why the `reset()`?

May you explain this to me? Thanks :)

**Comment by staudenmeir** [comment]
The code allows users to only provide a single record:

```php
User::upsert(['username' => 'foo'], 'username');
```

Otherwise, it would have to look like this:

```php
User::upsert([['username' => 'foo']], 'username');
             ^                     ^
```

**Comment by vlakoff** [comment]
Ah, right… Now I remember. This one is a common source of confusion…

Perfectly understood, thanks!
