### ISSUE TITLE
Call to undefined method upsert

### ISSUE THREAD

**Issue by mshoaibdev** [staudenmeir/laravel-upsert#11]
`Call to undefined method Illuminate\\Database\\Query\\Builder::upsert()`

Laravel ^6.2

**Comment by staudenmeir** [comment]
What does your query look like? What's the result of `composer dump`?

**Comment by mshoaibdev** [comment]
I tried with composer dump-autoload, but still the same issue.

**Comment by staudenmeir** [comment]
What's the output of `composer dump`?

**Comment by mshoaibdev** [comment]
The issue solved by reinstalling the package, I think it was the composer issue.
Thanks for responses.

**Comment by webds** [comment]
Hi, i have the same problem.

Call to undefined method Illuminate\\Database\\Query\\Builder::upsert()

Laravel 7

**Comment by staudenmeir** [comment]
@webds Please create a new issue.
