### ISSUE TITLE
Inser & Update Multiple rows on one hit

### ISSUE THREAD

**Issue by mshukurlu** [staudenmeir/laravel-upsert#13]
Hi friends,

Is is possible that I insert or Update multiple rows in one attempt with different values?.

I see on documentation it is possible for using multiple row insert/update with the same value.

Please let me know what is best practice using this for gaining more speed and decrease query counts ?

**Comment by staudenmeir** [comment]
How do you mean "same" and "different" values? Do you mean different tables?

**Comment by mshukurlu** [comment]
@staudenmeir  No friend ,

Please look at example :

> DB::table('stats')->upsert(
>     [
>         ['post_id' => 1, 'date' => now()->toDateString(), 'views' => 1],
>         ['post_id' => 2, 'date' => now()->toDateString(), 'views' => 1],
>     ],
>     ['post_id', 'date'],
>     ['views' => DB::raw('stats.views + 1')]
> );
> 

In this case the two object has the same value - 'views' => DB::raw('stats.views + 1')

I need like this : 

> [ ['views' => DB::raw('stats.views + 1')],['views' => DB::raw('stats.views + 2')]]

I hope my example is usefull for you to understand ,

I need to set a new value for every row.

I have solved my problem writing codes in my model already .But If your package has this feature this may be good to use (y)

**Comment by staudenmeir** [comment]
What database engine are you using?

Can you share your actual use case (or a simplified version)?

**Comment by mshukurlu** [comment]
@staudenmeir  I have answer_items table which contains answers given any survey on my survey system. While user save their answers on my survey system it need to store (the question size is changing based on survey may be its count is 10 in the other survey may be 125 or more )

Then I need to store them at once on my database (there is a function save and continue later also)
So If user has answer for question on answer_items table I need to update His answer else insert new.

**Comment by staudenmeir** [comment]
> I have solved this problem without package already on my model

With multiple queries or a single one?
