### ISSUE TITLE
Call to undefined method `upsert()`

### ISSUE THREAD

**Issue by andrewmclagan** [staudenmeir/laravel-upsert#14]
Receiving on Laravel  `^7.0` 

```bash
Call to undefined method Illuminate\Database\Query\Builder::upsert()
```

I believe the issue is related to another package we are using: [https://github.com/michaeldyrynda/laravel-efficient-uuid](https://github.com/michaeldyrynda/laravel-efficient-uuid)

In `Staudenmeir\LaravelUpsert\Connectors\ConnectionFactory::createConnection()` the custom connection is never used

**Comment by staudenmeir** [comment]
These packages do indeed interfere with each other.

Are you using `upsert()` on an Eloquent model? If so, you can add the `HasUpsertQueries` trait to the model: https://github.com/staudenmeir/laravel-upsert#eloquent

**Comment by andrewmclagan** [comment]
Perfect, I will inject the Builder via my service's constructor...! Thank you.
