### ISSUE TITLE
Add more examples?

### ISSUE THREAD

**Issue by nimabrownlee** [staudenmeir/laravel-upsert#15]
Is it possible to add more examples so a Laravel newbie like myself could also use the library. For example what would be the best way to update relationships?

Category `hasMany` Product

Should I add the `HasUpsertQueries` trait to the Category or Product model to run the statement below?

`category->products()->upsert([...])`

I want to update or create products that belong to a specific category. How would I solve that?

**Comment by staudenmeir** [comment]
Can you share the `products` migration?

**Comment by nimabrownlee** [comment]
@staudenmeir 

```
Schema::create('products', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->string('description')->nullable();
    $table->string('image')->nullable();
    $table->integer('price');
    $table->timestamps();

    $table->foreignId('category_id')->nullable()->constrained()->onDelete('set null');
});
```

**Comment by staudenmeir** [comment]
What does the data of new/changed products look like that you would provide to `upsert()` as the first argument?

**Comment by nimabrownlee** [comment]
Just bunch of JSON data, some of whom has been created or updated on the frontend.

```
{
  "id": 1,
  "name": "Product 1",
  "description": ...,
  "price": 79,
},
{
  "id": 2,
  "name": "Product 2",
  "description": ...,
  "price": 79,
},
```

**Comment by staudenmeir** [comment]
What is `id` for new products? Is it missing?

**Comment by nimabrownlee** [comment]
It's missing. Shouldn't laravel create it by default?

**Comment by staudenmeir** [comment]
The database creates it but using the package with an `AUTO_INCREMENT` primary key is not the most common use case and I want to test the solution before posting it.

What database are you using?

**Comment by nimabrownlee** [comment]
I use MySQL.

**Comment by staudenmeir** [comment]
The UPSERT query requires every record to have the same attributes:
- You need to add `id => null` to new records.
- You need to add the `category_id` to new records. You can use `null` for existing ones because the column doesn't get updated (I assume).

```php
$values = json_decode($json, true);

foreach ($values as $key => $value) {
    if (isset($value['id'])) {
        $values[$key]['category_id'] = null;
    } else {
        $values[$key]['id'] = null;

        $values[$key]['category_id'] = $category->id;
    }
}

Product::upsert($values, 'id', ['name', 'description', 'price']);
```

Here, `$json` would look like this: `[{"id": 1, ...}, {"name": "...", ...}, ...]`

Also be aware of this MySQL issue with gaps in auto-incremented IDs: https://stackoverflow.com/q/23516958/4848587

**Comment by nimabrownlee** [comment]
Thanks! So you can't use eloquent relationships but have to specify the `category_id`.

**Comment by staudenmeir** [comment]
Yes, at least for now. I'll take a look if I can make `$category->products()->upsert()` work.
