### ISSUE TITLE
Return affected rows on when calling upsert on Eloquent models

### ISSUE THREAD

**Issue by fuentesjr** [staudenmeir/laravel-upsert#16]
Currently the number of affected rows are returned when using the query builder interface:

```php
$affectedRows = DB::table('stats')->upsert(
    [
        ['post_id' => 1, 'date' => now()->toDateString(), 'views' => 1],
        ['post_id' => 2, 'date' => now()->toDateString(), 'views' => 1],
    ],
    ['post_id', 'date'],
    ['views' => DB::raw('stats.views + 1')]
);
```

However, the same is not true for the Eloquent model interface. I'm not sure if this is a defect or an enhancement.

```php
Stat::upsert(
    [
        ['post_id' => 1, 'date' => now()->toDateString(), 'views' => 1],
        ['post_id' => 2, 'date' => now()->toDateString(), 'views' => 1],
    ],
    ['post_id', 'date'],
    ['views' => DB::raw('stats.views + 1')]
);
```

**Comment by staudenmeir** [comment]
Both methods should return the same result. What does the Eloquent method return for you? What database are you using?

**Comment by fuentesjr** [comment]
The query builder returns an integer, but the eloquent method returns an instance of `Illuminate\Database\Eloquent\Builder`. This is on a mysql database and using Laravel 7. However, after adding the `HasUpsertQueries` trait, it began returning the affected rows count. From the README, the trait was only needed until Laravel 5.7 ... I presume something changed since then. Regardless, not really an issue.  However, after I added a test on a local branch of `laravel-upsert` on the number of affected rows, there is an inconsistency between at least sqlite and mysql. On an update from an upsert, mysql returns 2 while sqlite returns 1.

**Comment by staudenmeir** [comment]
You're right, I had only tested it with the trait. This is caused by the way Eloquent forwards the method call the underlying query builder. You can get the number of affected rows like this:

```php
$affectedRows = Stat::getQuery()->upsert(...);
```

> However, after I added a test on a local branch of laravel-upsert on the number of affected rows, there is an inconsistency between at least sqlite and mysql. On an update from an upsert, mysql returns 2 while sqlite returns 1.

MySQL's behavior is a bit special. From the [documentation](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html):

> With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values.

**Comment by fuentesjr** [comment]
@staudenmeir Thank you for the quick responses. The mysql behavior is indeed special, but I guess that's by design. I'll have to write separate queries to count the number of inserts and updates. In any case, thank you for taking the time to look into these things. I'll go ahead and close this gh issue.
