### ISSUE TITLE
Error when table name begins with number

### ISSUE THREAD

**Issue by roke22** [staudenmeir/laravel-upsert#17]
The records are not saved in the table if the name of the table begins with a number, for example "1_table".
I forget to say that is in postgresql with laravel 6

**Comment by staudenmeir** [comment]
Is there an error? What does your query look like?

**Comment by roke22** [comment]
There is no error, just didn't insert the row. I try to do again and paste some image but that will be in a few days. The query was like this example:

DB::table($bbdd)->upsert(
    ['id' => $id, 'name' => $name],
    'id'
);

Where $bbdd was a table name like "63_names".

Thank you.

**Comment by staudenmeir** [comment]
Does the query work with a "normal" table name?

**Comment by roke22** [comment]
Yes, works on a table name without numbers at the beginning. In postgresql
you must quote the table name if begins by numbers i mean: INSERT INTO
"65table" (id, name) VALUES (1, 'John')

Thank you.
Jose J. Anton

**Comment by staudenmeir** [comment]
The package does quote the table name and it works for me. Can you log the executed query?

**Comment by roke22** [comment]
Was my mistake, i try it again and now all rows are inserted correctly. Sorry for my mistake.
