### ISSUE TITLE
Trigger Events/Observers Like `saved`, `created`, or `updated`

### ISSUE THREAD

**Issue by paulrrogers** [staudenmeir/laravel-upsert#19]
This is a feature request to fire off events for observers methods such as `saved`, `created`, or `updated`. As it is one must manually do the work of the observers or explicitly trigger the events each time.

Ideally this could also work with preemptive observer methods like `saving`, `creating`, `updating`, etc.  And it could also add a non-static upserting method like `saveUpsert(array $update)`.

**Comment by staudenmeir** [comment]
Please #2 why that's not possible.
