### ISSUE TITLE
Eloquent Methods Not Triggering Model Touch Relationships

### ISSUE THREAD

**Issue by shatterproof** [staudenmeir/laravel-upsert#2]
It appears the Eloquent `upsert()` and `insertIgnore()` do not trigger model touch relationships for updating owner/parent timestamps as outlined here:

https://laraveldaily.com/eloquent-touch-for-models-and-their-relationships/

These are the relationships defined in the model as `$touches`.

**Comment by staudenmeir** [comment]
That's the correct behavior. You need to differentiate between methods like `Model::update()` and `Builder::update()`. Only the former one touches relationships, the latter one doesn't:

```php
// Fetches the model from the database and touches relationships.
User::find($id)->update($values);

// Executes the query directly in the database and doesn't touch relationships.
User::where('id', $id)->update($values); 
```

`upsert()` and `insertIgnore()` are `Builder` methods and can't touch relationships.
