### ISSUE TITLE
Model::upsert Returns Builder, Not Int

### ISSUE THREAD

**Issue by paulrrogers** [staudenmeir/laravel-upsert#20]
When I call `::upsert()` against a model class  it returns an Eloquent Builder instead of an integer of affected rows. This contradicts the documented return type. Is this a bug?

If I use `DB::table(…)` instead of the model then it returns the int.

**Comment by staudenmeir** [comment]
Please see https://github.com/staudenmeir/laravel-upsert/issues/16#issuecomment-649031852.
