### ISSUE TITLE
PGSQL support for RETURNING

### ISSUE THREAD

**Issue by mfn** [staudenmeir/laravel-upsert#21]
(quite some time passed since https://github.com/laravel/ideas/issues/1090 …)

My use-case for `RETURNING` is mostly about getting back:
- the primary key of newly inserted rows
- or the primary key of the modified row (in case of `DO UPDATE SET`)

For `DO NOTHING`, `RETURNING` won't return anything for the non-`INSERT` case.

The goal is avoid having to run a separate query to know _which_ rows where affected. I know I can run a separate query using an index (it's the base requirement for `ON CONFLICT` anyway), but I still rather avoid this for cases where a LOT of upserst / second can happen.

I've checked all my "upsert use-cases", and each of them takes advantage of this.

Would it in your opinion make sense to support this for PgSQL?

I don't use / can't comment on any support of this for other databases.

Looking at the sources in `\Staudenmeir\LaravelUpsert\Query\Builder::upsert` and `\Staudenmeir\LaravelUpsert\Query\Builder::insertIgnore`, it probably means:
- adding a new optional parameter for the columns to return (can be more than one)
- changing the signature of the method when such parameter is provdided

It would _probably_ make more sense to introduce a new `upsertReturning` (and `insertIgnoreReturning` respectively), but I don't want to get ahead of things.

Thanks

**Comment by staudenmeir** [comment]
Yeah, I agree that this would be really useful. I originally wanted to support all databases, but that's apparently not possible. 

I'll work on an implementation.

**Comment by mfn** [comment]
I forgot to mention that `WHERE` is also something missing, as in
```
INSERT INTO …(…)
VALUES(…)
ON CONFLICT (…)
DO UPDATE SET …
WHERE …
RETURNING …
```
😬

**Comment by mfn** [comment]
> I'll work on an implementation.

FTR, I did implement this in a (unfortunately) private codebase for now. It's a) not as featurefull and b) only Postgres

One interesting challenge I faced was that I _already had_ custom `ConncectionFactory` in place (or to be more clear: the equivalent for customized Grammar and similar stuff for Postgres), which actually would have clashes with this approach: replacing the service with a enhanced version makes compositing different features (almost? quite?) impossible.

I opted for an approach where I just tried to _get away_ with calling publicly available methods and and therefore provide the feature via a dedicated class, not part of any of the existing framework illuminate/database hierarchy.

This wasn't possible in all cases, that's why I created e.g. https://github.com/laravel/framework/pull/33953 so I don't have to duplicate logic what timestamps to update (it was reverted in 7.x but ultimately applied to 8.x). Though the code yet has to make use ofthis.

I tried to add `WHERE` support but faced the problem that I couldn't call `\Illuminate\Database\Query\Grammars\Grammar::compileWheres` from the _outside_, it's `protected`.
I didn't see a real pattern, there are quite some public `compile*` methods but also other protected ones.

Since I did not yet _had_ to port existing code to use this nicer WHERE feature, I didn't make a move yet.

----
I did mention all this because:
- ultimately, I likely cannot make use of this library due to this and wouldn't want anyone feeling like working on this for my issue when I already see I can't use it
- wanted to share some experience regarding extendability of the Laravel framework
  Personally I see Laravel very good in regards to being extendable as you can almost replace any part with your own, which however has downsides if multiple parties try to do this for different reasons.

----
Actually I figured since I already take time to write down my experience, there's no harm in sharing the code which basically _is yours_ but transformed; I'm not to credit for anything here:
```php
    /**
     * Version adapted from \Staudenmeir\LaravelUpsert\Query\Builder::upsert
     *
     * Note: can't use this version for cases when `WHERE` conditions would be required.
     * I tried to implement it, but I would need
     * `\Illuminate\Database\Query\Grammars\Grammar::compileWheres` to be public
     * to avoid extending the Grammar, which I rather would not do for this yet.
     *
     * (the referenced package does it but currently lacks the `RETURNING` feature)
     *
     * @param Builder $query
     * @param array<string,mixed> $values
     * @param array<string> $target
     * @param array<string,mixed> $update
     * @param array<string> $returning
     * @return array<stdClass>
     */
    public static function upsert(
        Builder $query,
        array $values,
        array $target,
        array $update,
        array $returning
    ): array {
        $grammar = $query->getGrammar();
        $connection = $query->getConnection();

        $sql = $grammar->compileInsert($query, $values);

        $sql .= ' ON CONFLICT (' . $grammar->columnize($target) . ')';

        if ($update) {
            $sql .= ' DO UPDATE SET ';

            $sql .= Collection
                ::make($update)
                ->map(fn ($value, $key) => $grammar->wrap($key) . ' = ' . $grammar->parameter($value))
                ->implode(', ');

            if ($returning) {
                $sql .= ' RETURNING ';

                $sql .= Collection
                    ::make($returning)
                    ->map(fn ($value) => $grammar->wrap($value))
                    ->implode(', ');
            }
        } else {
            $sql .= ' DO NOTHING';
        }

        $bindings = self::cleanBindings(
            array_merge(
                Arr::flatten($values, 1),
                Collection
                    ::make($update)
                    ->reject(fn ($value, $key) => is_int($key))
                    ->all(),
            )
        );

        return $connection->select($sql, $bindings);
    }

    /**
     * Remove all of the expressions from a list of bindings.
     *
     * @param array<mixed> $bindings
     * @return array<mixed>
     */
    protected static function cleanBindings(array $bindings): array
    {
        return array_values(
            array_filter(
                $bindings,
                fn ($binding) => !$binding instanceof Expression
            )
        );
    }
```
Interestingly, `cleanBindings` also couldn't be called from the builder as it's protected and the code would have benefited from it being publich. I guess I decided it wasn't worth it (for now) for what is ultimately a one-liner.

Btw, do you think the code attribution is "good enough" 🤔 Should it include more specifics than just the class reference?

Anyway, your code **did help** me come up with a better solution than I had before, so I tried my best to "give back" here.

Thank you!

**Comment by Ahmed-Aboud** [comment]
not sure if its related to "PGSQL"
but at least what i saw that for PGSQL even if you want to update all fields you better add $update
its x times faster than leaving $update empty
```
$update = $model->getFillable();
upsert($data, $uniqueIdentifier, $update)
```

**Comment by mfn** [comment]
Closing, as I'm using my own solution
