### ISSUE TITLE
Usage with UUIDs

### ISSUE THREAD

**Issue by faustbrian** [staudenmeir/laravel-upsert#22]
Currently trying to use this package in combination with something like https://github.com/michaeldyrynda/laravel-efficient-uuid which obviously won't work because it relies on the eloquent model events which are not triggered with this package from what I can tell due to it executing raw queries.

What would be the recommended way of using UUIDs with this package? Since the UUID can't be automatically handled through events I would probably need to manually generate it the first time a record is created but since it uses an UPSERT without any additional queries I don't have the knowledge about an existing record that matches all data, excluding the UUID, to know if I should generate the UUID.

**Comment by staudenmeir** [comment]
I'll look into it. What database are you using?

**Comment by faustbrian** [comment]
Usually using PostgreSQL.

**Comment by staudenmeir** [comment]
Is the UUID the table's primary key? Would you upsert a single model or multiple?

**Comment by faustbrian** [comment]
Most times I use a combination of an auto-incrementing primary key and a UUID for public-facing things like URLs but there are projects where I use UUIDs as primary keys. The current project would be using the first scenario.

I would be upserting both single and multiple models. There are certain jobs that bulk insert records because they are coming from a third-party.

**Comment by staudenmeir** [comment]
> There are certain jobs that bulk insert records because they are coming from a third-party.

What does this data look like? Are the UUIDs coming from the third-party?

**Comment by faustbrian** [comment]
The project I am working on at the moment has the need to generate its own UUIDs because the third-party doesn't provide proper UUIDs on its own but most of the time my needs for UUIDs are anyways that I need to generate them myself.

**Comment by staudenmeir** [comment]
Does the data contain UUIDs for the existing records or how does the matching with the database work?

**Comment by faustbrian** [comment]
When indexing third-party data there usually is a UUID already available on which I can rely for a unique index for upserting. When I use UUIDs internally in my application I use a package to generate them since I can rely on Eloquent Model Events but I need to use this package for certain models due to the amount of data is rapidly inserted where `updateOrCreate` performs quite badly which then brings me to the issue of not being able to let a package update or create the UUID on-the-fly.

**Comment by staudenmeir** [comment]
> I would probably need to manually generate it the first time a record is created but since it uses an UPSERT without any additional queries I don't have the knowledge about an existing record that matches all data, excluding the UUID, to know if I should generate the UUID.

So when a record in your input data doesn't have a UUID, it doesn't necessarily mean that it doesn't exist yet, right? If it does already exist, do you need to fetch its UUID (or do anything else) or do you just move on to the next record?

**Comment by faustbrian** [comment]
Correct, if a record doesn't have a UUID it could still exist because the UUID would be generated by me when the records are inserted into the database for the first time. If the record already exists I just would want to update the existing record and move on.

**Comment by staudenmeir** [comment]
UPSERT queries can't handle this case, but you should still be able to speed up the whole process with the package:
1. Go through the records without a UUID and run a `SELECT` query for each one to get their UUID if they already exist. If so, add the UUID to the record.
2. Generate a UUID for the remaining records without a UUID.
3. Use the package's `upsert()` with the whole records array and provide the UUID column as the second argument.

**Comment by faustbrian** [comment]
That's what I am currently doing, was hoping for there to be an easier way. Thanks for looking into this.
