### ISSUE TITLE
Possibly merge to the core

### ISSUE THREAD

**Issue by paras-malhotra** [staudenmeir/laravel-upsert#23]
Thanks for the awesome package!

`InsertOrIgnore` has already made it to the framework core. I'd suggest we could possibly add a PR for `upsert` into the core as well. The current `updateOrInsert` supports only a single record and a bulk upsert operation would be a great addition to the core imo!

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by paras-malhotra** [comment]
This is implemented in https://github.com/laravel/framework/pull/34698 with a small change: I've removed the third optional argument.

**Comment by paras-malhotra** [comment]
Merged in https://github.com/laravel/framework/pull/34698 and https://github.com/laravel/framework/pull/34712
