### ISSUE TITLE
access to binding parameter  in update array

### ISSUE THREAD

**Issue by Mghobadid** [staudenmeir/laravel-upsert#24]
`DB::table('stats')->upsert(
    [
        ['post_id' => 1, 'date' => now()->toDateString(), 'views' => 1],
        ['post_id' => 2, 'date' => now()->toDateString(), 'views' => 1],
    ],
    ['post_id', 'date'],
    ['views' => DB::raw('stats.views +'.$post_id)]
);`
 
how access post_id when update?

**Comment by staudenmeir** [comment]
What database are you using?

**Comment by Mghobadid** [comment]
mysql 5.7.31

**Comment by staudenmeir** [comment]
You can get the value with `VALUES(post_id)`: https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html
