### ISSUE TITLE
What is the equivalent of updateOrCreate?

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [staudenmeir/laravel-upsert#25]

**Comment by staudenmeir** [comment]
That depends on your use case. `upsert()` and `updateOrCreate()` aren't directly comparable.

**Comment by diego-lipinski-de-castro** [comment]
I found this package looking for a alternative to updateOrCreate, I am not sure what is the relation now, can you give an use case example?

**Comment by staudenmeir** [comment]
How are you using `updateOrCreate()` at the moment?
