### ISSUE TITLE
Differences between laravel-upsert and Laravel 8.10's native upsert

### ISSUE THREAD

**Issue by Vusys** [staudenmeir/laravel-upsert#27]
First of all, a massive thank you @staudenmeir for this package.

I'm working on updating an application from Laravel 7 to 8. It was going well until 8.10 rolled around with its own implementation of upserting. Before 8.10, this just worked with Laravel 8. With 8.10, the method signatures of Laravel's upsert and laravel-upsert differ resulting in a fatal error.

I've removed laravel-upsert from my application and rewrote the upsert usages to reflect Laravel's signature. The resulting queries are identical as far as I can tell.

I'm wondering if there's anything in this package that is not in Laravel core? Potentially some edge cases I'm missing. Our database is running MySQL 5.7, code is Laravel 8.x, PHP 7.4.

**Comment by staudenmeir** [comment]
I haven't had time to fully compare the implementations. I'll update you with the result.

**Comment by finallyRaunak** [comment]
@staudenmeir : here is the error details that I am getting after upgrading illuminate/database to `v8.11.2`.

`Declaration of Staudenmeir\LaravelUpsert\Query\Builder::upsert(array $values, $target, ?array $update = NULL) should be compatible with Illuminate\Database\Query\Builder::upsert(array $values, $uniqueBy, $update = NULL)`

**Comment by staudenmeir** [comment]
@finallyRaunak Please see https://github.com/staudenmeir/laravel-upsert/issues/26.

**Comment by staudenmeir** [comment]
I'm pretty sure there are no relevant differences. I ran the package's tests against the new native Laravel implementation and they all passed.

**Comment by intergalactisch** [comment]
@staudenmeir Congrats of having your package implemented in the core of Laravel! Is it me, or can't I use the DB::raw overrides (such as proposed here https://github.com/staudenmeir/laravel-upsert/issues/9) in Laravel's version?

**Comment by staudenmeir** [comment]
@intergalactisch What SQL does Laravel (try to) execute in your case?

**Comment by intergalactisch** [comment]
When I run it like this:
```
ShopProduct::upsert(
    $productArray,
    ['productcode'],
    [
       'image' => DB::raw("if(`image` is null, values(`image`), `image`)"),
    ]);
```
I get the following error:
```
SQLSTATE[HY000]: General error: 1 near "values": syntax error (SQL: insert into "shop_products" ("created_at", "image", "name", "productcode", "slug", "updated_at") values (2020-11-18 21:52:03, /var/folders/y_/whnvprxj6hx514qmgwj_lb740000gn/T/cf46d09ad8845c9ff742a9045090d252.png, tempora, 6011295759374531, tempora, 2020-11-18 21:52:03), (2020-11-18 21:52:03, /var/folders/y_/whnvprxj6hx514qmgwj_lb740000gn/T/d0842fcf4ea08a4dab9f82e9456fdd36.png, qui, 4024007178334, qui, 2020-11-18 21:52:03) on conflict ("productcode") do update set "image" = if(`image` is null, values(`image`), `image`), "updated_at" = "excluded"."updated_at")
```

**Comment by staudenmeir** [comment]
@intergalactisch The raw expression only works with MySQL.

**Comment by intergalactisch** [comment]
Thanks for the quick reply! I am using Laravel Valet, and as far as I know I am using MySQL (or MariaDB I guess) :0.

**Comment by staudenmeir** [comment]
@intergalactisch Are you running tests on SQLite? Laravel is not generating this query for MySQL/MariaDB.

**Comment by intergalactisch** [comment]
Lol @staudenmeir you are right, *sigh*. Sorry, my bad..👍

**Comment by mpyw** [comment]
Alternative but different approach: [mpyw/laravel-retry-on-duplicate-key: Automatically retry non-atomic upsert operation when unique key constraints are violated.](https://github.com/mpyw/laravel-retry-on-duplicate-key)

CC to participants in laravel/framework#19372 (@Gogtsu @Yismen @alessandro-aglietti @alessandrolattao @aligajani @amenk @amirasyraf @bhuvidya @cg-rsands @chimit @comtelindodev @didioh @driesvints @duq @eduardodallmann @flexgrip @gbwashleybrown @hxgdzyuyi @idezigns @kcassam @msdavid1296 @mst101 @msztorc @novaknole @paulrrogers @rajjanorkar @simonmaass @sweebee @themsaid @tonviet712 @waleedakhlaq @whande1992)
