### ISSUE TITLE
upgrade SQLite to the required version (3.24.0)

### ISSUE THREAD

**Issue by rachediabdenacer** [staudenmeir/laravel-upsert#28]
hi :hand:  

```
PHP : 7.4
Laravel : 8.10.0
Sqlite : 3.22.0
Ubuntu : 18.04
```

i'm using your package but i have a problem regarding the sqlite version.

at the beginning, i had the version `3.22.0` of sqlite on my pc, that's why i have this error message :

> `SQLSTATE[HY000]: General error: 1 near "on": syntax error (SQL: insert into "offer_option_choices" ("condition_map", "created_at", "id", "offer_option_id", "updated_at", "value") values (my new condition, 2020-11-12 17:40:30, eb8fe6f5-8eb0-4b49-8e0d-26f7a06dc3e5, 91fe0a73-16d2-4c3d-9aaa-2505451cd619, 2020-11-12 17:40:30, my new value), (my updated condition, 2020-11-12 17:40:30, 91fe0a73-1760-40b8-8aec-3cfff23767b8, 91fe0a73-16d2-4c3d-9aaa-2505451cd619, 2020-11-12 17:40:30, my updated value) on conflict ("id") do update set "value" = "excluded"."value", "condition_map" = "excluded"."condition_map", "updated_at" = "excluded"."updated_at")`

I know the minimum required version of sqlite is `3.24.0`, for that, i upgraded it on my pc to the latest version `3.34.0`, but on `phpinfo()` it still shows me the version `3.22.0` and it didn't want to change

I don't know how to update the **sqlite.so** php extension to the required version !

![image](https://user-images.githubusercontent.com/26568444/98978010-963e2f80-2519-11eb-838b-189ec968b5e1.png)

![image](https://user-images.githubusercontent.com/26568444/98978092-b40b9480-2519-11eb-8541-e1e3e0dcf3fc.png)

![image](https://user-images.githubusercontent.com/26568444/98978124-c1c11a00-2519-11eb-93d2-86d06080668f.png)

**Comment by staudenmeir** [comment]
Yeah, that's quite tricky. You can try replacing your `libsqlite3.so` and `pdo_sqlite.so` with the precompiled libraries I'm using for the package's automated tests:
https://github.com/staudenmeir/php-sqlite/tree/master/3.30.1
https://github.com/staudenmeir/php-sqlite/tree/master/3.30.1/7.4
https://github.com/staudenmeir/laravel-upsert/blob/master/.github/workflows/ci.yml#L48

**Comment by rachediabdenacer** [comment]
Hello @staudenmeir ,
Thank you for your reply,
I did exactly what you told me, and it worked great, thank you very much for your help.
