### ISSUE TITLE
How to get inserted or updated id?

### ISSUE THREAD

**Issue by elxavier129** [staudenmeir/laravel-upsert#29]
I need to get id from inserted data or updated data, is there a way to get it after ran upsert? Thanks

**Comment by staudenmeir** [comment]
Unfortunately, this is complicated issue. What database are you using? Are you upserting a single row or multiple?

**Comment by elxavier129** [comment]
MySQL, it just a single row data.

**Comment by staudenmeir** [comment]
Add `'id' => DB::raw('LAST_INSERT_ID(id)')` to the columns to be updated (third argument). Then you can get the `id` with `lastInsertId()` in both cases:

```php
DB::table('users')->upsert(
    [...],
    'username',
    ['active', 'updated_at', 'id' => DB::raw('LAST_INSERT_ID(id)')]
);

dump(DB::getPdo()->lastInsertId());
```

**Comment by phiLuee** [comment]
I need to return the id to the eloquent model with upsert - saving 500 rows in a bulk. Need the id for further relations with other tables. Is there any possibility? Acutally I'm saving every single row with "push()"Method of the eloquent model for getting the id (PK).

i'm using mysql, later on oracle db and mssql.

**Comment by staudenmeir** [comment]
@phiLuee Unfortunately, that's not possible for multiple rows.

**Comment by phiLuee** [comment]
@staudenmeir thanks for that info :)
