### ISSUE TITLE
Unable to add to project (Laravel v6.18)

### ISSUE THREAD

**Issue by ItsJoeTurner** [staudenmeir/laravel-upsert#30]
> Could not find a matching version of package staudenmeir/laravel-upsert

Anyone else? I have ran the composer install text just as in the documentation.

**Comment by staudenmeir** [comment]
What version of Laravel are you using?

**Comment by staudenmeir** [comment]
What does the whole error look like?

**Comment by ItsJoeTurner** [comment]
<img width="563" alt="Screen Shot 2021-06-04 at 18 44 28" src="https://user-images.githubusercontent.com/1974465/120796443-05867a00-c565-11eb-8e5d-5945250c9a8d.png">

**Comment by staudenmeir** [comment]
That's a weird one. Are you using the latest Composer version? Do other packages work?

**Comment by ItsJoeTurner** [comment]
Updating to 2.1.1 of Composer gives me a more refined error, but it's still not available. No issues with other packages or Composer in general. I'm in Asia, could it be something to do with that? The CDN maybe?
<img width="994" alt="Screen Shot 2021-06-04 at 18 56 19" src="https://user-images.githubusercontent.com/1974465/120797731-9b6ed480-c566-11eb-9c49-680c2d58f4ae.png">

**Comment by staudenmeir** [comment]
Yeah, looks like an issue in this direction. Not sure what to do expect trying again in a few hours/tomorrow.

**Comment by ItsJoeTurner** [comment]
The issue is the same when using VPN. Weird.

**Comment by ItsJoeTurner** [comment]
This is what it's trying to connect to: 

https://packagist.phpcomposer.com/p2/staudenmeir/laravel-upsert.json

It's 404

**Comment by ItsJoeTurner** [comment]
All good. For anyone that comes across this, here's the fix if your composer is using a mirror: 

https://pkg.phpcomposer.com/

See "Remove mirroring:"
