### ISSUE TITLE
Not working with PHP 8

### ISSUE THREAD

**Issue by iwasherefirst2** [staudenmeir/laravel-upsert#31]
I get this when I try to install it:

Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - staudenmeir/laravel-upsert[v1.0, ..., 1.0.x-dev] require illuminate/database 5.5.*|5.6.*|5.7.* -> found illuminate/database[v5.5.0, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - staudenmeir/laravel-upsert[v1.1, ..., 1.1.x-dev] require php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
    - staudenmeir/laravel-upsert v1.2 requires php ^7.2 -> your php version (8.0.7) does not satisfy that requirement.
    - staudenmeir/laravel-upsert v1.3 requires php ^7.2.5 -> your php version (8.0.7) does not satisfy that requirement.
    - staudenmeir/laravel-upsert v1.4 requires php ^7.3 -> your php version (8.0.7) does not satisfy that requirement.
    - Root composer.json requires staudenmeir/laravel-upsert ^1.0 -> satisfiable by staudenmeir/laravel-upsert[v1.0, ..., v1.4].
```
Is there really a conflict for PHP 8 or can the requriements be changed?

**Comment by staudenmeir** [comment]
What version of Laravel are you using?

**Comment by pilot-max** [comment]
I am unable to install via composer.

PHP 8.0.10
Laravel 8.65.0

Composer output:
  Problem 1
    - staudenmeir/laravel-upsert[v1.0, ..., 1.0.x-dev] require illuminate/database 5.5.*|5.6.*|5.7.* -> found illuminate/database[v5.5.0, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - staudenmeir/laravel-upsert[v1.1, ..., 1.1.x-dev] require php ^7.1.3 -> your php version (8.0.10) does not satisfy that requirement.
    - staudenmeir/laravel-upsert v1.2 requires php ^7.2 -> your php version (8.0.10) does not satisfy that requirement.
    - staudenmeir/laravel-upsert v1.3 requires php ^7.2.5 -> your php version (8.0.10) does not satisfy that requirement.
    - staudenmeir/laravel-upsert v1.4 requires php ^7.3 -> your php version (8.0.10) does not satisfy that requirement.
    - Root composer.json requires staudenmeir/laravel-upsert ^1.0 -> satisfiable by staudenmeir/laravel-upsert[v1.0, ..., v1.4].

**Comment by mdmuzaffer** [comment]
Update your composer.json file with my below code and then add your added package under "require": { } object, It will work
don't forget run command update composer


{
"name": "laravel/laravel",
"type": "project",
"description": "The Laravel Framework.",
"keywords": ["framework", "laravel"],
"license": "MIT",
"require": {
		"php": "^7.3|^8.0",
		"fideloper/proxy": "^4.4",
		"fruitcake/laravel-cors": "^2.0",
		"guzzlehttp/guzzle": "^7.0.1",
		"laravel/framework": "^8.40",
		"laravel/socialite": "^5.3",
		"laravel/tinker": "^2.5",
		"dompdf/dompdf": "^1.0",
		"intervention/image": "^2.5",
		"maatwebsite/excel": "^3.1",
		"softon/indipay": "^1.2"
	},
"require-dev": {
"facade/ignition": "^2.5",
"fakerphp/faker": "^1.9.1",
"laravel/sail": "^1.0.1",
"laravel/ui": "^3.3",
"mockery/mockery": "^1.4.2",
"nunomaduro/collision": "^5.0",
"phpunit/phpunit": "^9.3.3"
},
"autoload": {
	"psr-4": {
		"App\\": "app/"
	},
	"classmap": [
		"database/seeds",
		"database/factories"
	],
	 "files": [
	"app/helper/helpers.php"
	]
},
"autoload-dev": {
	"psr-4": {
		"Tests\\": "tests/"
	}
},

"scripts": {
	"post-autoload-dump": [
		"Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
		"@php artisan package:discover --ansi"
	],
	"post-root-package-install": [
		"@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
	],
	"post-create-project-cmd": [
		"@php artisan key:generate --ansi"
	]
},

"extra": {
"laravel": {
"dont-discover": []
}
},
"config": {
"optimize-autoloader": true,
"preferred-install": "dist",
"sort-packages": true
},
"minimum-stability": "dev",
"prefer-stable": true
}
