### ISSUE TITLE
PHP 8 compatibility with Laravel 6.0

### ISSUE THREAD

**Issue by adrenth** [staudenmeir/laravel-upsert#35]
Hi @staudenmeir,

Thank you for this wonderful addition to the Laravel framework. Currently we're using this package in October CMS (based on Laravel 6 LTS) and we would like to upgrade our project to PHP 8.0. Unfortunately version 1.2 of this package prevents us from upgrading. It would be great to have support for PHP 8.0 for the Laravel 6.0 version of this package.

Problem 1
-  Root composer.json requires staudenmeir/laravel-upsert 1.2 -> satisfiable by staudenmeir/laravel-upsert[v1.2].
- staudenmeir/laravel-upsert v1.2 requires php ^7.2 -> your php version (8.0.14; overridden via config.platform, same as actual) does not satisfy that requirement.

**Comment by adrenth** [comment]
Not sure how to submit a PR, but I think adding this to composer.json would allow us to upgrade to PHP 8.

```json
"php": "^7.2 || ^8.0",
```

**Comment by staudenmeir** [comment]
I released a new version for PHP 8.0.
