### ISSUE TITLE
Eloquent Model fill updated_at field only if any other field changes

### ISSUE THREAD

**Issue by BusinessClick** [staudenmeir/laravel-upsert#38]
Hi,
I didn't find a way to update timestamp field `updated_at` during Eloquent Model upsert ONLY IF a row has a field changed.
Laravel Models change the `updated_at` field if `isDirty() = true`.
You write into documentation that `updated_at` is added to Eloquent Models and it's true, but it always added and updated even also no field changes.

Do you have suggestions?
Thanks so much!

**Comment by staudenmeir** [comment]
Hi @BusinessClick,
I've looked into this in the past but haven't found a good solution. If you are using MySQL/MariaDB, you could probably build something like this: https://stackoverflow.com/a/16588699/4848587

**Comment by staudenmeir** [comment]
Thanks!
