### ISSUE TITLE
PostgreSQL Error - How to fix it?

### ISSUE THREAD

**Issue by tulaeff** [staudenmeir/laravel-upsert#7]
`Illuminate\Database\QueryException  : SQLSTATE[21000]: Cardinality violation: 7 ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time`

I have array with some items, and I try add all this items in DB. And may be there are more than one duplicate rows, it is normal case for my situation, script must always update it for setting last value from source (I use it in seeders). May be, I can configure PostgreSQL to fix it? Thanks.

**Comment by staudenmeir** [comment]
Please post the table schema (with indices), your query, and the whole error message.

**Comment by simonoff** [comment]
You have duplicates in the query.

**Comment by tulaeff** [comment]
> You have duplicates in the query.

Да это понятно. Непонятно как заставить PostgreSQL обновлять не один раз, а при каждом совпадении.

**Comment by simonoff** [comment]
а он этого и не будет делать. у вас в массиве данных что вы передаете есть дубликаты, вот он и матерится.

**Comment by staudenmeir** [comment]
I can only help you if you post the details I asked for.
