### ISSUE TITLE
collision error

### ISSUE THREAD

**Issue by wimil** [staudenmeir/laravel-upsert#8]
I am using a cache package for the models, but wanting to use your package with eloquent models tells me collision error, it is because your package cancels newEloquentBuilder (). Is there any way to fix it? thanks.

cache pack I am using:
https://github.com/GeneaLabs/laravel-model-caching

**Comment by staudenmeir** [comment]
I'll look into it.

**Comment by wimil** [comment]
thanks ... waiting

**Comment by ilyasfoo** [comment]
So far there's no known elegant way to do this. Others have tried to merge multiple Builders https://github.com/grimzy/laravel-mysql-spatial/issues/17#issuecomment-330094672
