### ISSUE TITLE
Possible to only update database record column value when empty?

### ISSUE THREAD

**Issue by intergalactisch** [staudenmeir/laravel-upsert#9]
Hi, 

Thanks for the awesome package. Is it possible to only update a value if it is empty in the updated record?

For example, I have a database with products that have an "image" column. I am using upsert to quickly insert new or update existing products. When a product already exists in the database, the update is fired. With this, is there an easy way to check if the database product already has a value in image, and if now, update it?

**Comment by staudenmeir** [comment]
What database are you using?

**Comment by intergalactisch** [comment]
MariaDB

**Comment by staudenmeir** [comment]
Does "empty" mean an empty string or `null`?

**Comment by intergalactisch** [comment]
Preferably `null`, but whatever comes closest 😄

**Comment by staudenmeir** [comment]
It's possible with a raw expression:

```php
Product::upsert(
    $values,
    $target,
    [
        'image' => DB::raw("if(`image` is null, values(`image`), `image`)"),
        // TODO: Add the other columns that should be updated.
    ]
);
```

**Comment by intergalactisch** [comment]
Thanks! Works like a charm!
